import { Inter, Roboto }from "next/font/google"
import "./globals.css";
import Navbar from "@/components/Shared/Navbar/Navbar";
import Footer from "@/components/Shared/Footer/Footer";
import AuthProvider from "@/services/AuthProvider";


const roboto = Roboto({weight : ['300', '400', '900'],subsets: ["latin"]})
const inter = Inter({weight : ['300', '400', '900'],subsets: ["latin"]})

export const metadata = {
  title: {
    default: "Next Hero",
    template: "%s | Next Hero"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
        <Navbar/>
        {children}
        <Footer/>
        </AuthProvider>
        
      </body>
    </html>
  );
}
